telebot:
  logger:
    root:
      level: 10 # DEBUG level, see https://docs.python.org/2/library/logging.html#levels
#      level: 20 # INFO level
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    tornado:
#      level: 10 # DEBUG level, see https://docs.python.org/2/library/logging.html#levels
      level: 20 # INFO level
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  api_key: blah-blah-blah
  ephemeral_storage_plugin: local_storage
  persistent_storage_plugin: local_storage
  plugins: duckduckgo_search
